import { Exercise, ExerciseCategory } from './types';

export const exercises: Exercise[] = [
  // ── SHOULDERS ──────────────────────────────────────────────────────────────
  {
    id: 'sh-machine-press',
    name: 'Machine Shoulder Press',
    category: 'shoulders',
    equipment: ['machine'],
    defaultSets: 3,
    defaultReps: '10–12',
    defaultWeight: '60 lbs',
  },
  {
    id: 'sh-db-overhead-press',
    name: 'DB Overhead Press',
    category: 'shoulders',
    equipment: ['dumbbells'],
    defaultSets: 3,
    defaultReps: '10',
    defaultWeight: '30 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=qEwKCR5JCog',
  },
  {
    id: 'sh-arnold-press',
    name: 'Arnold Press',
    category: 'shoulders',
    equipment: ['dumbbells'],
    defaultSets: 3,
    defaultReps: '10',
    defaultWeight: '25 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=3ml7BH7mNwQ',
  },
  {
    id: 'sh-lateral-raise',
    name: 'Dumbbell Lateral Raises',
    category: 'shoulders',
    equipment: ['dumbbells'],
    defaultSets: 3,
    defaultReps: '15',
    defaultWeight: '10–15 lbs',
  },
  {
    id: 'sh-cable-lateral-raise',
    name: 'Dual Cable Lateral Raise',
    category: 'shoulders',
    equipment: ['cable'],
    defaultSets: 3,
    defaultReps: '15',
    defaultWeight: '10 lbs each',
    youtubeUrl: 'https://www.youtube.com/watch?v=PPbqIqMmVQg',
  },
  {
    id: 'sh-chest-sup-lateral',
    name: 'Chest Supported Lateral Raise',
    category: 'shoulders',
    equipment: ['dumbbells', 'bench'],
    defaultSets: 3,
    defaultReps: '15',
    defaultWeight: '15 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=FeJcaD3_d1U',
  },
  {
    id: 'sh-cable-face-pull',
    name: 'Cable Face Pull',
    category: 'shoulders',
    equipment: ['cable'],
    defaultSets: 3,
    defaultReps: '15',
    defaultWeight: '30–40 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=V8dZ3pyiCBo',
  },
  {
    id: 'sh-rear-delt-pec-deck',
    name: 'Rear Delt Pec Deck (Reverse Fly)',
    category: 'shoulders',
    equipment: ['machine'],
    defaultSets: 3,
    defaultReps: '15',
    defaultWeight: '50 lbs',
  },
  {
    id: 'sh-front-raise',
    name: 'Alternating DB Front Raises',
    category: 'shoulders',
    equipment: ['dumbbells'],
    defaultSets: 3,
    defaultReps: '15',
    defaultWeight: '10 lbs',
  },

  // ── BICEPS ─────────────────────────────────────────────────────────────────
  {
    id: 'bi-hammer-curl',
    name: 'Alternating Hammer Curls',
    category: 'biceps',
    equipment: ['dumbbells'],
    defaultSets: 3,
    defaultReps: '12 each',
    defaultWeight: '25 lbs',
  },
  {
    id: 'bi-incline-curl',
    name: 'Incline Seated DB Curl',
    category: 'biceps',
    equipment: ['dumbbells', 'bench'],
    defaultSets: 3,
    defaultReps: '10',
    defaultWeight: '20–25 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=G2LsOBD8p60',
  },
  {
    id: 'bi-crossbody-hammer',
    name: 'Cross Body Hammer Curls',
    category: 'biceps',
    equipment: ['dumbbells'],
    defaultSets: 3,
    defaultReps: '12 each',
    defaultWeight: '25–30 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=CFBZ4jN1CMI',
  },
  {
    id: 'bi-spider-curl',
    name: 'Spider Curl',
    category: 'biceps',
    equipment: ['dumbbells', 'bench'],
    defaultSets: 3,
    defaultReps: '12',
    defaultWeight: '20 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=DPoJJmnJaQg',
  },
  {
    id: 'bi-reverse-curl',
    name: 'Reverse Curls',
    category: 'biceps',
    equipment: ['dumbbells'],
    defaultSets: 3,
    defaultReps: '12',
    defaultWeight: '15–20 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=nwMDuBd0Y3M',
  },
  {
    id: 'bi-cable-curl',
    name: 'Cable Bicep Curl',
    category: 'biceps',
    equipment: ['cable'],
    defaultSets: 3,
    defaultReps: '12',
    defaultWeight: '40–50 lbs',
  },
  {
    id: 'bi-concentration-curl',
    name: 'Concentration Curl',
    category: 'biceps',
    equipment: ['dumbbells'],
    defaultSets: 3,
    defaultReps: '12 each',
    defaultWeight: '20–25 lbs',
  },
  {
    id: 'bi-21s',
    name: '21s (DB Curl)',
    category: 'biceps',
    equipment: ['dumbbells'],
    defaultSets: 3,
    defaultReps: '7/7/7',
    defaultWeight: '15–20 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=cX_ghWJx8nQ',
  },

  // ── TRICEPS ────────────────────────────────────────────────────────────────
  {
    id: 'tri-overhead-rope',
    name: 'Overhead Rope Tricep Extension',
    category: 'triceps',
    equipment: ['cable'],
    defaultSets: 3,
    defaultReps: '12–15',
    defaultWeight: '35–40 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=_gsUck-7M74',
  },
  {
    id: 'tri-skull-crusher',
    name: 'DB Skull Crusher',
    category: 'triceps',
    equipment: ['dumbbells', 'bench'],
    defaultSets: 3,
    defaultReps: '12',
    defaultWeight: '25–30 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=IQoO8BtkKvM',
  },
  {
    id: 'tri-pushdown',
    name: 'Cable Tricep Pushdown (Rope)',
    category: 'triceps',
    equipment: ['cable'],
    defaultSets: 3,
    defaultReps: '15',
    defaultWeight: '40–50 lbs',
  },
  {
    id: 'tri-sa-pushdown',
    name: 'Single Arm Neutral Grip Pushdown',
    category: 'triceps',
    equipment: ['cable'],
    defaultSets: 3,
    defaultReps: '12 each',
    defaultWeight: '20 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=Vj0qlmTLrGw',
  },
  {
    id: 'tri-lying-extension',
    name: 'Lying Tricep Extension',
    category: 'triceps',
    equipment: ['dumbbells', 'bench'],
    defaultSets: 3,
    defaultReps: '12',
    defaultWeight: '30–40 lbs',
  },
  {
    id: 'tri-bench-dips',
    name: 'Bench Dips',
    category: 'triceps',
    equipment: ['bench'],
    defaultSets: 3,
    defaultReps: 'MAX',
    defaultWeight: 'Bodyweight',
  },
  {
    id: 'tri-band-kickback',
    name: 'Band Tricep Kickback',
    category: 'triceps',
    equipment: ['resistance band'],
    defaultSets: 3,
    defaultReps: '15 each',
    defaultWeight: 'Light band',
    youtubeUrl: 'https://www.youtube.com/watch?v=wTRyc7GdNtk',
  },
  {
    id: 'tri-diamond-pushup',
    name: 'Diamond Push Ups',
    category: 'triceps',
    equipment: ['bodyweight'],
    defaultSets: 3,
    defaultReps: 'MAX',
    defaultWeight: 'Bodyweight',
  },

  // ── CHEST ──────────────────────────────────────────────────────────────────
  {
    id: 'ch-smith-incline',
    name: 'Smith Machine Incline Press',
    category: 'chest',
    equipment: ['smith machine'],
    defaultSets: 3,
    defaultReps: '10/8/6',
    defaultWeight: '70/80/90 lbs',
  },
  {
    id: 'ch-db-incline',
    name: 'DB Incline Press',
    category: 'chest',
    equipment: ['dumbbells', 'bench'],
    defaultSets: 3,
    defaultReps: '10',
    defaultWeight: '30–35 lbs',
  },
  {
    id: 'ch-alt-db-incline',
    name: 'Alternating DB Incline Press',
    category: 'chest',
    equipment: ['dumbbells', 'bench'],
    defaultSets: 3,
    defaultReps: '10 each',
    defaultWeight: '30 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=8iPEnn-ltC8',
  },
  {
    id: 'ch-pec-deck',
    name: 'Pec Deck (Chest Fly Machine)',
    category: 'chest',
    equipment: ['machine'],
    defaultSets: 3,
    defaultReps: '15',
    defaultWeight: '70–80 lbs',
  },
  {
    id: 'ch-cable-fly-low',
    name: 'Cable Chest Fly (Low to High)',
    category: 'chest',
    equipment: ['cable'],
    defaultSets: 3,
    defaultReps: '12',
    defaultWeight: '15–20 lbs each',
    youtubeUrl: 'https://www.youtube.com/watch?v=Iwe6AmxVf7o',
  },
  {
    id: 'ch-cable-crossover',
    name: 'Cable Crossover (High to Low)',
    category: 'chest',
    equipment: ['cable'],
    defaultSets: 3,
    defaultReps: '12',
    defaultWeight: '20–25 lbs each',
    youtubeUrl: 'https://www.youtube.com/watch?v=taI4XduLpTk',
  },
  {
    id: 'ch-chest-press-machine',
    name: 'Chest Press Machine',
    category: 'chest',
    equipment: ['machine'],
    defaultSets: 3,
    defaultReps: '12',
    defaultWeight: '80–100 lbs',
  },
  {
    id: 'ch-flat-db-press',
    name: 'DB Flat Bench Press',
    category: 'chest',
    equipment: ['dumbbells', 'bench'],
    defaultSets: 3,
    defaultReps: '10',
    defaultWeight: '40–50 lbs',
  },

  // ── BACK ───────────────────────────────────────────────────────────────────
  {
    id: 'ba-cable-row-vbar',
    name: 'Seated V-Bar Cable Row',
    category: 'back',
    equipment: ['cable'],
    defaultSets: 3,
    defaultReps: '12',
    defaultWeight: '60–70 lbs',
  },
  {
    id: 'ba-sa-cable-row',
    name: 'Single Arm Seated Cable Row',
    category: 'back',
    equipment: ['cable'],
    defaultSets: 3,
    defaultReps: '12 each',
    defaultWeight: '35–45 lbs',
  },
  {
    id: 'ba-chest-sup-row',
    name: 'Chest Supported DB Row',
    category: 'back',
    equipment: ['dumbbells', 'bench'],
    defaultSets: 3,
    defaultReps: '12',
    defaultWeight: '30–35 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=GZbfZ033f74',
  },
  {
    id: 'ba-sa-db-row',
    name: 'Single Arm DB Row',
    category: 'back',
    equipment: ['dumbbells', 'bench'],
    defaultSets: 3,
    defaultReps: '12 each',
    defaultWeight: '40–50 lbs',
  },
  {
    id: 'ba-lat-pulldown',
    name: 'Lat Pulldown Machine',
    category: 'back',
    equipment: ['machine'],
    defaultSets: 3,
    defaultReps: '12',
    defaultWeight: '80–100 lbs',
  },
  {
    id: 'ba-straight-arm-pulldown',
    name: 'Straight Arm Cable Pulldown',
    category: 'back',
    equipment: ['cable'],
    defaultSets: 3,
    defaultReps: '15',
    defaultWeight: '40–50 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=0H9l5bO0fJI',
  },
  {
    id: 'ba-underhand-row',
    name: 'Underhand Smith Machine Row',
    category: 'back',
    equipment: ['smith machine'],
    defaultSets: 3,
    defaultReps: '12',
    defaultWeight: '50–60 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=kBWAon7ItDw',
  },
  {
    id: 'ba-trx-row',
    name: 'TRX Rows',
    category: 'back',
    equipment: ['TRX'],
    defaultSets: 3,
    defaultReps: '12',
    defaultWeight: 'Bodyweight',
  },

  // ── PULL-UPS ───────────────────────────────────────────────────────────────
  {
    id: 'pu-assisted-machine',
    name: 'Machine Assisted Pull Ups',
    category: 'pullups',
    equipment: ['machine'],
    defaultSets: 3,
    defaultReps: '10',
    defaultWeight: 'Assist as needed',
  },
  {
    id: 'pu-band-assisted',
    name: 'Band Assisted Pull Ups',
    category: 'pullups',
    equipment: ['pull-up bar', 'resistance band'],
    defaultSets: 3,
    defaultReps: '8–10',
    defaultWeight: 'Light/medium band',
    youtubeUrl: 'https://www.youtube.com/watch?v=HRV5YKKaeVw',
  },
  {
    id: 'pu-negative',
    name: 'Negative Pull Ups',
    category: 'pullups',
    equipment: ['pull-up bar'],
    defaultSets: 3,
    defaultReps: '6–8 (5 sec lower)',
    defaultWeight: 'Bodyweight',
    youtubeUrl: 'https://www.youtube.com/watch?v=YPsOjNzP8vI',
  },
  {
    id: 'pu-trx',
    name: 'TRX Pull Ups',
    category: 'pullups',
    equipment: ['TRX'],
    defaultSets: 3,
    defaultReps: '10',
    defaultWeight: 'Bodyweight',
  },

  // ── LEGS ───────────────────────────────────────────────────────────────────
  {
    id: 'lg-goblet-squat',
    name: 'Pause Goblet Squat',
    category: 'legs',
    equipment: ['dumbbells'],
    defaultSets: 3,
    defaultReps: '10',
    defaultWeight: '25–35 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=MxsFDhcyFyE',
  },
  {
    id: 'lg-bulgarian-split',
    name: 'Bulgarian Split Squat (DB)',
    category: 'legs',
    equipment: ['dumbbells', 'bench'],
    defaultSets: 3,
    defaultReps: '8–10 each',
    defaultWeight: '20–30 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=2C-uNgKwPLE',
  },
  {
    id: 'lg-sumo-deadlift',
    name: 'Sumo KB Deadlift',
    category: 'legs',
    equipment: ['kettlebell'],
    defaultSets: 3,
    defaultReps: '12',
    defaultWeight: '40–60 lbs',
  },
  {
    id: 'lg-rdl',
    name: 'Romanian Deadlift (DB)',
    category: 'legs',
    equipment: ['dumbbells'],
    defaultSets: 3,
    defaultReps: '12',
    defaultWeight: '40–50 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=7j-2_xCcMUA',
  },
  {
    id: 'lg-hip-thrust',
    name: 'DB Hip Thrust',
    category: 'legs',
    equipment: ['dumbbells', 'bench'],
    defaultSets: 3,
    defaultReps: '12–15',
    defaultWeight: '50–65 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=xDmFkJxPzeM',
  },
  {
    id: 'lg-cossack-squat',
    name: 'Alternating Cossack Squats',
    category: 'legs',
    equipment: ['dumbbells'],
    defaultSets: 3,
    defaultReps: '12 each',
    defaultWeight: '15–20 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=tpczTeSkHz0',
  },
  {
    id: 'lg-leg-press',
    name: 'Leg Press Machine',
    category: 'legs',
    equipment: ['machine'],
    defaultSets: 3,
    defaultReps: '12',
    defaultWeight: '130–160 lbs',
  },
  {
    id: 'lg-leg-extension',
    name: 'Leg Extension Machine',
    category: 'legs',
    equipment: ['machine'],
    defaultSets: 3,
    defaultReps: '15',
    defaultWeight: '60–80 lbs',
  },
  {
    id: 'lg-leg-curl',
    name: 'Seated Leg Curl Machine',
    category: 'legs',
    equipment: ['machine'],
    defaultSets: 3,
    defaultReps: '12',
    defaultWeight: '60–70 lbs',
  },
  {
    id: 'lg-abductor',
    name: 'Machine Thigh Abductor',
    category: 'legs',
    equipment: ['machine'],
    defaultSets: 3,
    defaultReps: '15',
    defaultWeight: '80–90 lbs',
  },
  {
    id: 'lg-step-ups',
    name: 'DB Step Ups',
    category: 'legs',
    equipment: ['dumbbells', 'bench'],
    defaultSets: 3,
    defaultReps: '12 each',
    defaultWeight: '20–25 lbs',
  },
  {
    id: 'lg-walking-lunges',
    name: 'Walking Lunges (DB)',
    category: 'legs',
    equipment: ['dumbbells'],
    defaultSets: 3,
    defaultReps: '12 each',
    defaultWeight: '20–25 lbs',
  },
  {
    id: 'lg-split-squat-twist',
    name: 'Split Squat with Rotation',
    category: 'legs',
    equipment: ['dumbbells'],
    defaultSets: 3,
    defaultReps: '10 each',
    defaultWeight: '10 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=gcNh17Ckjgg',
  },

  // ── CORE ───────────────────────────────────────────────────────────────────
  {
    id: 'co-rkc-plank',
    name: 'RKC Plank',
    category: 'core',
    equipment: ['bodyweight'],
    defaultSets: 3,
    defaultReps: '30–40 sec',
    defaultWeight: 'Bodyweight',
    youtubeUrl: 'https://www.youtube.com/watch?v=OKN0QdApFkU',
  },
  {
    id: 'co-side-plank',
    name: 'Forearm Side Plank',
    category: 'core',
    equipment: ['bodyweight'],
    defaultSets: 3,
    defaultReps: '30 sec each',
    defaultWeight: 'Bodyweight',
  },
  {
    id: 'co-side-plank-abduct',
    name: 'Side Plank with Hip Abduction',
    category: 'core',
    equipment: ['bodyweight'],
    defaultSets: 3,
    defaultReps: '15 each',
    defaultWeight: 'Bodyweight',
    youtubeUrl: 'https://www.youtube.com/watch?v=OR06LwvJDIw',
  },
  {
    id: 'co-hollow-body',
    name: 'Hollow Body Hold',
    category: 'core',
    equipment: ['bodyweight'],
    defaultSets: 3,
    defaultReps: '30 sec',
    defaultWeight: 'Bodyweight',
    youtubeUrl: 'https://www.youtube.com/watch?v=LMn4OmUKHEA',
  },
  {
    id: 'co-oblique-vup',
    name: 'Oblique V-Ups',
    category: 'core',
    equipment: ['bodyweight'],
    defaultSets: 3,
    defaultReps: '15 each',
    defaultWeight: 'Bodyweight',
    youtubeUrl: 'https://www.youtube.com/watch?v=FZxjUCyKwDk',
  },
  {
    id: 'co-dead-bug',
    name: 'Dead Bug',
    category: 'core',
    equipment: ['bodyweight'],
    defaultSets: 3,
    defaultReps: '10 each',
    defaultWeight: 'Bodyweight',
    youtubeUrl: 'https://www.youtube.com/watch?v=g_BYB0R-4Ws',
  },
  {
    id: 'co-goblet-march',
    name: 'Goblet Weighted March',
    category: 'core',
    equipment: ['dumbbells'],
    defaultSets: 3,
    defaultReps: '20',
    defaultWeight: '20–25 lbs',
    youtubeUrl: 'https://www.youtube.com/watch?v=AJ9WEQ-8oVU',
  },
  {
    id: 'co-ab-wheel',
    name: 'Ab Wheel Rollout',
    category: 'core',
    equipment: ['ab wheel'],
    defaultSets: 3,
    defaultReps: '10',
    defaultWeight: 'Bodyweight',
    youtubeUrl: 'https://www.youtube.com/watch?v=2I9LlZJ7k_c',
  },
];

export function getByCategory(category: ExerciseCategory): Exercise[] {
  return exercises.filter((e) => e.category === category);
}

export function getById(id: string): Exercise | undefined {
  return exercises.find((e) => e.id === id);
}

export function getAlternative(currentId: string, category: ExerciseCategory, excludeIds: string[]): Exercise | null {
  const pool = getByCategory(category).filter(
    (e) => e.id !== currentId && !excludeIds.includes(e.id)
  );
  if (pool.length === 0) return null;
  return pool[Math.floor(Math.random() * pool.length)];
}
